default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5

development:
  <<: *default
  database: bookstore_dev
  host: localhost
  username: bookstore_admin
  password: password

test:
  <<: *default
  database: bookstore_test
  host: localhost
  username: bookstore_admin
  password: password


production:
  <<: *default
  database: bookstore_production
  timeout: 5000
  username: <%= ENV['BOOKSTORE_USER'] %>
  password:  <%= ENV['BOOKSTORE_PASSWORD'] %>